[theme]
base="dark"
primaryColor="#34d058"  # Customize the primary color as desired
backgroundColor="#0d1117"  # Set the background to a dark color
secondaryBackgroundColor="#161b22"  # Set a slightly lighter dark color for secondary backgrounds
textColor="#c9d1d9"  # Set the text color to a light gray

# Additional optional customizations
font="monospace"